"""Generate concise DPRs for S502-S512 from the registry."""
import json
from pathlib import Path

reg = json.loads(Path("D:/Arcanum/Projects/RMWND/Technical/series_registry.json").read_text(encoding="utf-8"))
out_dir = Path("D:/Arcanum/Projects/RMWND/Technical/docs/series")

SPECS = {
    "S502": {"source_col": "Mp",            "table": "H.1", "e2_col": "C_star_m",
             "narrative": "Constant capital consumed in production (M'_p in book notation, C*_m in extended notation). Subtracted from TP* to yield GFP.",
             "benchmark": "1948=198.47"},
    "S503": {"source_col": "GFP_star",      "table": "H.1", "e2_col": "GFP",
             "narrative": "Gross Final Product: GFP = TP* - C*_m. Identity-checked year-by-year against S501 and S502.",
             "benchmark": "1948=247.74"},
    "S504": {"source_col": "V_star",        "table": "H.1", "e2_col": None,
             "narrative": "Variable Capital: wages of productive labor under S&T's classification. Drives the rate of exploitation S506 and feeds extension formulas.",
             "benchmark": "1948=88.41, 1972=324.30, 1989=1206.40"},
    "S505": {"source_col": "S_star",        "table": "H.1", "e2_col": None,
             "narrative": "Surplus Value: S* = VA* - V*. Identity-checked against VA_star and V_star in H.1.",
             "benchmark": "1948=149.94, 1972=645.98, 1989=2943.35"},
    "S506": {"source_col": "S_star_V_star", "table": "H.1", "e2_col": None,
             "narrative": "Rate of Exploitation: e = S*/V*. The book's central Marxian magnitude. Identity-checked against S505/S504 ratio.",
             "benchmark": "1948=1.70, 1958=2.01, 1967=2.10, 1972=1.99, 1977=2.10, 1989=2.44"},
    "S507": {"source_col": "(derived)",     "table": "—",   "e2_col": None,
             "narrative": "Surplus Ratio S*/(S*+V*). Derived from S505 and S504 directly; no source column. Equivalent to S*/VA*.",
             "benchmark": "1948=0.57, 1989=0.60"},
    "S511": {"source_col": "T511A",         "table": "5.7", "e2_col": None,
             "narrative": "Productive Labor Share (Lp/L). The share of total employment classified as productive. Falls secularly 1948-1989 from 0.57 to 0.36.",
             "benchmark": "1948=0.57, 1958=0.52, 1967=0.51, 1977=0.50, 1989=0.36"},
    "S512": {"source_col": "T512A",         "table": "5.7", "e2_col": None,
             "narrative": "Productive Wage Share (V*/W). The share of total wage bill paid to productive labor. Feeds the e = 1.238/(V*/W) - 1 extension formula for S506.",
             "benchmark": "1948=0.54, 1958=0.49, 1967=0.452, 1977=0.412, 1989=0.36"},
}

TEMPLATE = """# {sid} — {name}

**Chapter**: 5 — The Marxian Categories: Empirical Estimates
**Source Table**: Appendix {table}{e2_note}
**Units**: {units}
**Period**: 1948-1989 (book period; extension via {ext} when API access provisioned)
**Content Type**: {content_type}
**Status**: book_period_validated

---

## Definition

{narrative}

---

## Subseries

{subseries_block}

---

## Construction

### {sid}-A (book period, 1948-1989)

1. Read `data/source/book_tables/{source_file}`.
2. {load_step}
3. {transform_step}

{cross_check_block}

---

## Reference Values (Validation Benchmarks)

{benchmark}

Tolerance class: `{tol_class}`{tol_detail}.

Validator: `code/V03_validators/V03_{sid}_{slug}.py` writes to `data/intermediate/validation/{sid}.json`.

---

## Provenance Chain

```
data/source/book_tables/{source_file}
  └── code/L01_loaders/L01_{sid}_{slug}.py
       └── data/intermediate/{sid}.csv
            └── code/P02_processors/P02_{sid}_{slug}.py
                 └── data/final/{sid}.csv
                      └── code/V03_validators/V03_{sid}_{slug}.py
```

---

## Citations

Shaikh, Anwar, and E. Ahmet Tonak. 1994. *Measuring the Wealth of Nations: The Political Economy of National Accounts*. Cambridge University Press. {citation_detail}

---

*Generated by anu-ingestion (re-authored from scratch against the Anu Framework v10.0 standard).*
"""

SLUGS = {
    "S502": "constant_capital", "S503": "gross_final_product",
    "S504": "variable_capital", "S505": "surplus_value",
    "S506": "exploitation_rate", "S507": "surplus_ratio",
    "S511": "productive_labor_share", "S512": "productive_wage_share",
}

UNITS_TOL = {
    "billions_usd": ("dollar_series", "rel 0.01 / abs 1.0"),
    "ratio":        ("rate_series",   "rel 0.001 / abs 0.01"),
    "share":        ("share_series",  "rel 0.05 / abs 0.02"),
}

written = []
for sid, spec in SPECS.items():
    entry = reg["series"][sid]
    units = entry.get("units", "")
    tol_class, tol_detail = UNITS_TOL.get(units, ("rate_series", ""))

    table_label = spec["table"]
    if table_label == "H.1":
        source_file = "book_tableH1_1948_1989.csv"
        e2_note = f" (cross-checked vs. Appendix E.2 column `{spec['e2_col']}` for 1948-1961 overlap)" if spec["e2_col"] else ""
        load_step = f"Extract column `{spec['source_col']}` (and the `year` index)."
        transform_step = "No further transformation — this is the canonical published value."
        cross_check_block = (
            f"Reference cross-check: Appendix E.2 column `{spec['e2_col']}` provides the same values for 1948-1961 — "
            f"V03 validates the H.1-derived series against E.2 row-by-row."
        ) if spec["e2_col"] else (
            "Validator includes an identity check that verifies the algebraic relation against other already-built series in this chapter."
        )
        citation_detail = f"Appendix H (Annual Time Series), p. 324-327. Cross-check vs. Appendix E.2 (Revenue Accounts, p. 310)."
    elif table_label == "5.7":
        source_file = "Table5_7_KeyRatios.csv"
        e2_note = ""
        load_step = f"Extract column `{spec['source_col']}` (book-authoritative values; the `T{sid[1:]}` column without the A-suffix is the replicator-recomputed comparison and is not used here)."
        transform_step = "No further transformation — this is the canonical published value."
        cross_check_block = "Validator checks the loaded series against the published benchmark years from validation_config.json."
        citation_detail = "Table 5.7 (Key Ratios), Chapter 5."
    else:
        source_file = "(derived from S505 and S504)"
        e2_note = ""
        load_step = "Load S505-A and S504-A from `data/final/`."
        transform_step = "Compute year-by-year: value = S_star / (S_star + V_star)."
        cross_check_block = "Validator checks against book-published surplus ratios at benchmark years."
        citation_detail = "Derived measure; book-period benchmarks from validation_config.json."

    subseries_block = "| Subseries | Source | Period | Units |\n|---|---|---|---|\n"
    for ssid, ssdata in entry.get("subseries", {}).items():
        period = ssdata.get("period", ["?", "?"])
        subseries_block += f"| `{ssid}` | {ssdata.get('source','')} | {period[0]}-{period[1]} | {ssdata.get('units','')} |\n"

    ext = "BEA NIPA + BLS CES" if entry.get("extension") else "n/a (book period only)"

    text = TEMPLATE.format(
        sid=sid, name=entry["name"], table=table_label, e2_note=e2_note,
        units=units, ext=ext, content_type=entry.get("content_type","time_series"),
        narrative=spec["narrative"], subseries_block=subseries_block.rstrip(),
        source_file=source_file, load_step=load_step, transform_step=transform_step,
        cross_check_block=cross_check_block, benchmark=spec["benchmark"],
        tol_class=tol_class, tol_detail=f" ({tol_detail})" if tol_detail else "",
        slug=SLUGS[sid], citation_detail=citation_detail,
    )
    out_path = out_dir / f"{sid}_DPR.md"
    out_path.write_text(text, encoding="utf-8")
    written.append((sid, out_path.stat().st_size))

print(f"Wrote {len(written)} DPRs:")
for sid, size in written:
    print(f"  {sid}_DPR.md ({size} bytes)")
