"""Generate DPRs for S508, S509, S515, S516, and pending stubs for S510, S513, S514."""
from pathlib import Path

out_dir = Path("D:/Arcanum/Projects/RMWND/Technical/docs/series")

s508 = """# S508 — Productive Consumption (CON*)

**Chapter**: 5 — The Marxian Categories
**Source Table**: Appendix E.2 (Revenue Accounts), p. 310
**Units**: billions current $
**Period**: 1948-1961 (book-period partial; later years require digitization of E.2 second half not in salvaged KB)
**Content Type**: time_series
**Status**: book_period_partial_1948_1961

## Definition

Productive Consumption (CON*) is total household consumption attributable to productive activities under the book's Marxian classification. Distinguished from total CON by excluding the unproductive (trade/finance/government services) share.

## Source

`data/source/book_tables/TableE2_RevenueAccounts_1948_1961.csv`, column `CON_star`. Loader: `L01_S508_productive_consumption.py` — direct column projection. Processor `P02_S508` is a pass-through.

## Reference

Validation benchmark from `validation_config.json` T508: 1948 = 158.46. PASS verified.

## Provenance

```
TableE2_RevenueAccounts_1948_1961.csv (col CON_star)
  -> L01_S508 -> data/intermediate/S508.csv
  -> P02_S508 -> data/final/S508.csv
  -> V03_S508 -> data/intermediate/validation/S508.json (PASS)
```

## Coverage Caveat

14-year coverage (1948-1961) is limited by what was digitized in the salvaged KB. To extend through 1989 we would need either (a) digitization of E.2's full appendix (pages 310+ of the book, not yet in the salvaged tables/), or (b) reconstruction from NIPA Table 2.4 plus the productive-sector concordance the book defines in Appendix C. Neither is yet provisioned. Status reflects this honestly rather than fabricating values.

---

*Generated by anu-ingestion (re-authored from scratch).*
"""

s509 = """# S509 — Productive Investment (IG*)

**Chapter**: 5
**Source Table**: Appendix E.2, p. 310
**Units**: billions current $
**Period**: 1948-1961
**Content Type**: time_series
**Status**: book_period_partial_1948_1961

## Definition

Productive Investment (IG*) is the share of total investment IG attributable to productive sectors under the book's classification. The remainder is unproductive investment (finance, trade, government).

## Source

`TableE2_RevenueAccounts_1948_1961.csv`, column `IG_star`. Loader L01_S509 -> processor P02_S509 (pass-through) -> validator V03_S509.

## Reference

No published numerical benchmark in `validation_config.json` for T509. Validator uses round-trip check against the raw E.2 row (1948 = 44.27). PASS verified.

## Coverage Caveat

Same as S508: 14-year limit reflects what is in the salvaged KB. Extension would require either the full E.2 digitization or NIPA reconstruction.

---

*Generated by anu-ingestion (re-authored from scratch).*
"""

s515 = """# S515 — Productive Employment (Lp), narrow classification

**Chapter**: 5
**Source Table**: Appendix E.3 (Labor Statistics), p. 320, row `Lp_total`
**Units**: thousands of workers
**Period**: 1948-1961
**Content Type**: time_series
**Status**: book_period_partial_1948_1961

## Definition

Total productive employment count, summed across sectors with the book's NARROW productive classification (which is more conservative than the BROAD classification used in Table 5.7 / S511).

## Classification Note (important)

The book uses two productive labor definitions:

- **Broad** (Table 5.7, S511): Lp/L = 0.57 in 1948. Includes a wider set of activities as productive.
- **Narrow** (Table E.3, S515): Lp/L = 0.453 in 1948. More conservative; excludes some borderline categories.

Both are book-published. They serve different analytical purposes:
- S511 (broad) drives the exploitation rate decomposition (V*/W).
- S515 (narrow) is the headcount basis for sector-by-sector labor reconciliation.

The new build keeps BOTH series as first-class, with this DPR documenting the boundary distinction. Cross-checking the two ratios is a useful sensitivity analysis but a difference is not a bug.

## Source

`TableE3_LaborStatistics.csv` is wide-by-year (years 1948-1961 are column headers, sectors are rows). The L01 loader transposes the Lp_total row to a year-indexed series.

## Reference

`Lp_total` row values verified directly:
- 1948 = 29,937 thousand
- 1961 = 33,615 thousand
Validator PASS.

## Coverage Caveat

E.3 in the salvaged KB covers 1948-1961 only. The full classification through 1989 would require Tables E.3-continued (later book pages) or BLS CES extension under the same productive boundary definition (non-trivial).

---

*Generated by anu-ingestion (re-authored from scratch).*
"""

s516 = """# S516 — Unproductive Employment (Lu = L - Lp), narrow classification

**Chapter**: 5
**Source Table**: Appendix E.3, p. 320, rows `L_total` and `Lp_total`
**Units**: thousands of workers
**Period**: 1948-1961
**Content Type**: derived
**Status**: book_period_partial_1948_1961

## Definition

Unproductive labor headcount, computed as the residual: Lu = L_total - Lp_total. Uses the same narrow classification as S515 (TableE3 source).

## Source / Construction

No separate L01 loader. The P02 processor reads `TableE3_LaborStatistics.csv` directly, extracts the `L_total` and `Lp_total` rows, and computes Lu year-by-year. Both rows are pre-existing in the book table; no extrapolation.

## Reference

Validation benchmarks computed directly from the E.3 row values:
- 1948 = 66,091 - 29,937 = 36,154 thousand
- 1961 = 82,827 - 33,615 = 49,212 thousand
Validator PASS.

## Coverage Caveat

Same as S515: 14-year coverage from salvaged E.3 only.

---

*Generated by anu-ingestion (re-authored from scratch).*
"""

s510_pending = """# S510 — Value Composition of Capital (K/V*) — PENDING

**Chapter**: 5
**Status**: pending_capital_stock_data
**Units**: ratio
**Content Type**: derived

## What this series is

The value composition of capital is the ratio of constant capital STOCK (K*, not the flow Mp) to variable capital (V*). It is a structural ratio describing how much accumulated past production sits behind each dollar of present-day wages.

## Why it is pending

The new build has S504 (V*) ready, but K* — the productive constant capital stock — is not yet sourced. K* requires either:

1. BEA Fixed Assets Table 4.1 (NAICS net stock by industry) with the book's productive-sector concordance applied, **or**
2. Digitization of Appendix Table H.2 or J (capital stock series) which is not in the salvaged KB.

The ST2 build derived K_star_by_industry as an intermediate output, but the new build's "from scratch" mandate requires going back to the BEA primary source rather than inheriting a derived intermediate from ST2.

## Acceptance criteria for activation

S510 is gated on:

- [ ] K* time series available in `data/source/` (either book-digitized or BEA-API-fetched)
- [ ] DPR updated with the exact source path and column
- [ ] L01_S510 / P02_S510 / V03_S510 written
- [ ] Validated against book Table 5.8 (if benchmark exists) or registry expected_range

The series is registered in `series_registry.json` so the pipeline accounts for it; the `status` field reads `pending_capital_stock_data`. No values are fabricated in the meantime (per the no-synthetic-data rule).

---

*Generated by anu-ingestion (placeholder DPR; activate when K* source is provisioned).*
"""

s513_pending = """# S513 — Marxian Profit Rate (r* = S*/(C* + V*)) — PENDING

**Chapter**: 5
**Status**: pending_capital_stock_data
**Units**: rate
**Content Type**: derived

## What this series is

The Marxian rate of profit, the central macroeconomic variable of Marxian political economy. Computed as surplus value divided by the sum of constant capital STOCK and variable capital: r* = S* / (C* + V*). Unlike orthodox profit-rate measures, it uses Shaikh & Tonak's productive/unproductive distinction throughout.

## Why it is pending

S513 depends on:

- S505 (S*) — DONE
- S504 (V*) — DONE
- C* = productive constant capital STOCK (K*) — **MISSING**, same dependency as S510

Until K* is sourced (see S510 DPR), r* cannot be computed.

## Acceptance criteria

Same as S510. Activation produces L01/P02/V03 trio plus extension methodology against BEA Fixed Assets for 1990-2024.

The book's r* trends are a primary research finding — the secular decline 1948-1989 is interpreted in Chapter 5 — so getting this right is high-priority for a definitive replication.

---

*Generated by anu-ingestion (placeholder DPR; activate when K* source is provisioned).*
"""

s514_pending = """# S514 — Capacity-Adjusted Profit Rate (r*_adj = r* × TCU) — PENDING

**Chapter**: 5
**Status**: pending_capital_stock_data
**Units**: rate
**Content Type**: derived

## What this series is

The Marxian profit rate adjusted for capacity utilization: r*_adj = r* × TCU, where TCU is the Federal Reserve total industrial capacity utilization index. The adjustment isolates the trend in the underlying profit rate from cyclical variation in how much capital stock is actually in use.

## Why it is pending

S514 depends on:

- S513 (r*) — pending (depends on K*)
- TCU (Federal Reserve series TCU) — not yet sourced, needs FRED API or cached pull

## Acceptance criteria

- [ ] S513 activated (with K* sourced)
- [ ] TCU time series loaded (FRED series ID `TCU`, monthly aggregated to annual)
- [ ] L01_S514 / P02_S514 / V03_S514 written

TCU is a public Federal Reserve series; provisioning requires only an API key or a one-time cached fetch. Once K* is in place, S514 is fast to enable.

---

*Generated by anu-ingestion (placeholder DPR; activate when S513 and TCU are provisioned).*
"""

dprs = {
    "S508_DPR.md": s508,
    "S509_DPR.md": s509,
    "S515_DPR.md": s515,
    "S516_DPR.md": s516,
    "S510_DPR.md": s510_pending,
    "S513_DPR.md": s513_pending,
    "S514_DPR.md": s514_pending,
}

for fname, content in dprs.items():
    (out_dir / fname).write_text(content, encoding="utf-8")
print(f"Wrote {len(dprs)} DPRs:")
for fname in dprs:
    print(f"  {fname}")
