"""Generate Wave 3 DPRs: S901 (implemented) + 7 pending stubs."""
import json
from pathlib import Path

OUT = Path("D:/Arcanum/Projects/RMWND/Technical/docs/series")

s901 = """# S901 — Summary Indicators (Chapter 9 Summary Table)

**Chapter**: 9 — Marxian National Accounts: Summary
**Source**: composed from S506, S511, S512, S608 final CSVs (with placeholders for S513, S514)
**Units**: mixed (ratio / rate / share by column)
**Period**: 1948-1989 (book), with row-by-row pending markers where K* / TCU
required for S513 / S514
**Content Type**: time_series
**Status**: book_period_validated (partial — pending K* unlocks 88 of 252 cells)

## Definition

The book's Chapter 9 summary aggregates the headline Marxian magnitudes into a single table so a reader can see all the key ratios side-by-side year-by-year. The new build constructs this purely from already-validated upstream series — no new source data:

- `S506` exploitation rate `e = S*/V*`
- `S511` productive labor share `Lp/L`
- `S512` productive wage share `V*/W`
- `S513` Marxian profit rate `r* = S*/(C*+V*)`  — **pending K\* (Wave 3 follow-up)**
- `S514` capacity-adjusted profit rate `r*_adj = r*·TCU`  — **pending K\* and TCU**
- `S608` NSW/V* ratio (from Wave 2)

## Construction

Purely aggregative. The P02 processor reads each upstream `data/final/{sid}.csv`, projects the `{sid}-A` subseries, and emits one long-format row per (year, indicator) pair. Pending indicators are explicit NaN (not synthesized).

## Validation

V03 round-trips: for every populated cell, S901 = upstream final/X.csv at the matching year, abs_err < 1e-9. PASS at 164/164 populated pairs across 4 columns × 41 years.

## Coverage gap

88 cells (S513 + S514 columns × all years) are NaN. They activate when K* is sourced. The DPR explicitly does NOT carry guessed values — the no-synthetic-data rule.

---

*Generated by anu-ingestion (re-authored from scratch).*
"""

pending_stubs = {
    "S201": ("Alternative GFP Measures",
             "Chapter 2's orthodox-vs-Marxian GDP comparison: GFP* (book series, S503) "
             "vs orthodox GDP/CFC/NDP (from BEA NIPA Table 1.1.5).",
             "needs NIPA GDP/CFC/NDP data 1929-2024 (BEA API or salvaged macro CSV)",
             ["Provision BEA NIPA loader (or salvage from ST2's API_Data cache)",
              "Compute GFP_GDP_ratio = S503 / GDP and FP_NDP_ratio = (S503 - depreciation) / NDP",
              "Write L01_S201 / P02_S201 / V03_S201"]),
    "S401": ("A-Matrix (I-O Technical Coefficients)",
             "Chapter 4's input-output A-matrix for benchmark BEA I-O years (1947, 1958, "
             "1963, 1967, 1972, 1977). The matrix itself is too large for a single CSV — "
             "the series stores summary metrics (n_sectors, sparsity, max_eigenvalue, "
             "condition number, productive/unproductive sector counts) per benchmark year.",
             "needs IO matrix data — BEA Benchmark Use/Make/Z tables, not in salvaged KB",
             ["Provision IO matrix loader (BEA Benchmark Use & Make tables in raw form, "
              "or matrix-summary CSV if pre-computed)",
              "Apply S&T productive/unproductive partition per Appendix C",
              "Compute per-year summary statistics; write S401 series"]),
    "S402": ("B-Matrix (Leontief Inverse)",
             "Chapter 4's Leontief inverse `(I - A)^-1`, derived from S401's A-matrix. "
             "Stores summary metrics per benchmark year (max element, sum, eigenvalue "
             "structure).",
             "depends on S401 — same I-O matrix data",
             ["Activate S401 first", "Compute B = (I - A)^-1 per benchmark year",
              "Emit per-year summary statistics"]),
    "S701": ("Labor Values",
             "Chapter 7's per-sector labor values (hours per unit output, derived from "
             "I-O coefficients + sectoral employment). Benchmark years only.",
             "needs S401 A-matrix + sectoral employment data",
             ["Activate S401", "Load BLS CES sectoral employment for benchmark years",
              "Compute labor values via Leontief inverse"]),
    "S702": ("Prices of Production",
             "Chapter 7's prices of production (cost prices including average profit "
             "rate). Computed from S401 + average rate of profit r*. Benchmark years only.",
             "needs S401 + S513 (Marxian profit rate, pending K*)",
             ["Activate S401 AND S513", "Compute prices of production"]),
    "S703": ("Value-Price Deviations",
             "Chapter 7's percent deviation between labor values (S701) and prices of "
             "production (S702). The book's central finding: deviations small but "
             "systematic — labor value is a good first approximation to price.",
             "depends on S701 and S702",
             ["Activate S701 and S702", "Compute (S702 - S701) / S701 * 100"]),
    "S801": ("Cross-Study Comparison",
             "Chapter 8 compares Shaikh-Tonak's exploitation rate and labor share against "
             "Mohun (2005) and other alternative classifications. Pulls together S506, "
             "S511 and the ES14## (Mohun 2005) replications.",
             "depends on ES1401-ES1404 (Mohun 2005), which are in Wave 4 scope",
             ["Activate Wave 4 (external study replications)",
              "Compute side-by-side comparison table"]),
}

PENDING_TEMPLATE = """# {sid} — {name} — PENDING

**Chapter**: {ch}
**Status**: pending_data_sourcing
**Content Type**: {ctype}
**Units**: {units}

## What this series is

{narrative}

## Why it is pending

{reason}

## Acceptance criteria for activation

{criteria}

## Faithfulness considerations

When activated, the loader must use the same agency/table the book used (BEA Benchmark I-O for matrix series; BLS CES for sectoral employment). No proxy substitutions per the Anu Extension Standard.

---

*Generated by anu-ingestion (pending DPR; activate when prerequisites are met).*
"""

REG = json.loads(Path("D:/Arcanum/Projects/RMWND/Technical/series_registry.json").read_text(encoding="utf-8"))

(OUT / "S901_DPR.md").write_text(s901, encoding="utf-8")
print("Wrote S901_DPR.md (implemented)")

for sid, (name, narrative, reason, criteria_list) in pending_stubs.items():
    entry = REG["series"][sid]
    criteria_md = "\n".join([f"- [ ] {c}" for c in criteria_list])
    text = PENDING_TEMPLATE.format(
        sid=sid, name=name, ch=entry.get("chapter","?"),
        ctype=entry.get("content_type","?"),
        units=entry.get("units","?"),
        narrative=narrative, reason=reason, criteria=criteria_md,
    )
    (OUT / f"{sid}_DPR.md").write_text(text, encoding="utf-8")
    print(f"Wrote {sid}_DPR.md (pending)")

# Also update statuses in registry
for sid in pending_stubs:
    REG["series"][sid]["status"] = "pending_data_sourcing"
REG["series"]["S901"]["status"] = "book_period_validated"
Path("D:/Arcanum/Projects/RMWND/Technical/series_registry.json").write_text(
    json.dumps(REG, indent=2, ensure_ascii=False), encoding="utf-8")
print("Updated registry statuses for Wave 3 series.")
