"""Generate Wave 5 (analytical) DPRs."""
from pathlib import Path

OUT = Path("D:/Arcanum/Projects/RMWND/Technical/docs/series")

DPRS = {
    "AS001": ("Social Burden Rate", "pending_capital_stock_data", """**Chapter**: 5/7 analytical
**Status**: pending_capital_stock_data
**Units**: ratio
**Content Type**: derived

## What this series is

The book's CENTRAL Chapter 7 analytical finding: decomposition of surplus value into net profit, taxes, and unproductive expenses:

```
S* = Pn + T + Eu
b  = (T + Eu) / S* = 1 - Pn/S*  (social burden rate)
```

Book finding 1948-1989: b rises 0.56 → 0.66 (16% increase) — workers' surplus increasingly absorbed by state and unproductive sectors rather than reinvested as productive capital.

## Why it is pending

Computing b requires:
- S505 (S*) — DONE
- Pn (NIPA net profit) — needs BEA NIPA Table 1.10/6.x
- T (total state taxes from production) — needs S604 ✓ + corporate tax data
- Eu (unproductive expenses) — needs K* and unproductive sector concordance

The Pn term in particular requires BEA NIPA loader, blocking activation.

## Activation criteria

- [ ] BEA NIPA loader (same blocker as S201)
- [ ] Unproductive sector concordance applied to NIPA breakdown
- [ ] Compute b = 1 - Pn/S*, validate against book Table 7.1 endpoints

---

*Generated by anu-ingestion.*
"""),
    "AS002": ("Khanjian Cross-Validation", "book_period_validated", """**Chapter**: 5 analytical (Section 5.10)
**Status**: book_period_validated
**Units**: ratio
**Content Type**: derived

## What this series is

Cross-validation of our S506 (rate of exploitation) against Khanjian (1989), as discussed in book Section 5.10 / Table 5.12. Khanjian re-estimated S*/V* using a different treatment of unincorporated income (treating it ALL as profit), which produces estimates ~20% higher than Shaikh & Tonak's.

This series stores 5 benchmark-year comparisons (1958, 1963, 1967, 1972, 1977) with columns: S506 value, Khanjian's e_star_rev (revised money-form), Khanjian's e_rev (revised labor-value form), and the percent gap between our S506 and Khanjian's estimates.

## Findings

Our S506 vs Khanjian's e_star_rev: gaps of 19-31% across the 5 benchmark years. Direction matches book — Khanjian is higher than ST. Magnitude slightly larger than the book's reported "~20%" because Khanjian's revisions also use updated NIPA vintages.

Validator PASS: all 5 gaps are positive (Khanjian > ST) and < 50% (rule of thumb).

## Source

Khanjian (1989) values hardcoded from book Table 5.12 (5 benchmark years). S506 values from `data/final/S506.csv`. Pure analytical composition; no new external source file.

---

*Generated by anu-ingestion.*
"""),
    "AS003": ("Unproductive Worker Exploitation Rate", "book_period_validated", """**Chapter**: Appendix I analytical
**Status**: book_period_validated
**Units**: ratio
**Content Type**: derived

## What this series is

The exploitation rate among UNPRODUCTIVE workers, from book Appendix I (Table I.1). Derived from our S506 via the book's formula:

```
eu = (hu/hp) / (ec_u/ec_p) × (1 + S*/V*) − 1
```

Where:
- hu/hp ≈ 0.99 (productive vs unproductive labor hours per week, near-constant)
- ec_u/ec_p (compensation ratio, from book Table I.1, hardcoded — converges from 1.13 in 1948 to 1.01 in 1989)
- S*/V* is our S506

## Findings

eu rises from **1.37 (1948) to 2.37 (1989)** — about a 75% increase, paralleling but slightly LOWER than S506's increase (1.70 → 2.44, 44% increase, but eu starts from a lower base). The ratio eu/ep converges from ~0.80 to ~0.97, confirming the book's finding that unproductive worker exploitation catches up to productive worker exploitation by the late 1980s.

Validator PASS at both endpoints (1948=1.3655, 1989=2.3719).

## Source

ec_u/ec_p table from book Appendix I.1, encoded in the P02 script as a year-keyed dictionary. S506 values from `data/final/S506.csv`. Pure analytical derivation.

---

*Generated by anu-ingestion.*
"""),
    "AS004": ("Marxian Productivity", "pending_capital_stock_data", """**Chapter**: Appendix J analytical (Table J.1)
**Status**: pending_capital_stock_data
**Units**: index
**Content Type**: derived

## What this series is

Marxian vs orthodox productivity comparison (book Appendix J):

```
q* = TPr / Hp    (Marxian: real total product per productive worker hour)
y* = GFPr / Hp   (quasi-Marxian: real GFP per productive worker hour)
y  = GDPr / H    (orthodox: real GDP per total worker hour)
```

Book finding 1948-1989: q* grows 183% (~2.83x) while orthodox y grows only 90% (~1.90x). Marxian productivity grows 2-3x FASTER than orthodox productivity. The "productivity slowdown" post-1972 is worse in y than in q*.

## Why it is pending

Requires:
- TP* (S501) — DONE
- GFP* (S503) — DONE
- Hp (productive labor HOURS, not just count) — needs BLS CES sectoral employment × hours per worker, full 1948-1989. We only have S515 14 years.
- GDP deflator (FRED series GDPDEF or BEA Table 1.1.4) — not yet loaded

## Activation criteria

- [ ] BLS CES sectoral employment + average hours loaded (Wave 4 follow-up infrastructure)
- [ ] FRED GDPDEF loader provisioned (same as for S201 / Moos)
- [ ] L01_AS004 reads TPr=S501/deflator, GFPr=S503/deflator, GDPr=GDP/deflator; computes Hp=PAYEMS×Lp/L
- [ ] Validate against book Table J.1 endpoints

---

*Generated by anu-ingestion.*
"""),
}

for sid, (name, _, body) in DPRS.items():
    title = f"# {sid} — {name}\n\n" + body
    (OUT / f"{sid}_DPR.md").write_text(title, encoding="utf-8")
    print(f"Wrote {sid}_DPR.md")
