"""Generate Sprint 1 DPRs."""
from pathlib import Path

OUT = Path("D:/Arcanum/Projects/RMWND/Technical/docs/series")

DPRS = {
    "S617": ("Employee Compensation (EC)", "**Chapter**: 6 (supporting). **Status**: book_period_validated. **Period**: 1948-1989. **Units**: billions_usd.\n\n## Definition\n\nTotal compensation of all employees (productive + unproductive) — the denominator for ST 1987 / ST 2002 NSW ratios. Loaded from Appendix H.1 column `EC`.\n\n## Construction\n\nPass-through from `data/source/book_tables/book_tableH1_1948_1989.csv` column `EC`.\n\n## Reference\n\n1948 = 142.09B; 1989 = 3079.00B. Validator PASS at both endpoints.\n\n## Why this is a series\n\nWhile EC is intermediate to many downstream ratios, registering it as a first-class series (S617) means every ratio that uses it (ES1101-1103, ES1201-1202, future productivity series) has a single audited source.\n"),

    "ES1501": ("Working Class Unproductive Labor (Mohun 2013)", "**Chapter**: External study — Mohun (2013). **Status**: book_period_validated. **Period**: 1948-1989. **Units**: thousands of workers.\n\n## Definition\n\nUnproductive workers in the *working class* component of total unproductive labor (excluding managerial/supervisory). Mohun's 2013 RRPE paper decomposes total Lu into Working Class (Luw) and Managerial (Lum) categories.\n\n## Source\n\n`data/source/external_studies/Mohun_unproductive_decomposition_1948_1989.csv`, column `Luw_mohun`. 1948=6,426K; 1989=24,674K.\n\n## Citation\n\nMohun, Simon. 2013. 'Unproductive Labor in the U.S. Economy 1964-2010.' Review of Radical Political Economics 46(3): 355-379.\n"),

    "ES1502": ("Managerial Unproductive Labor (Mohun 2013)", "**Status**: book_period_validated. Source: same Mohun decomposition CSV, column `Lum_mohun`. 1948=7,669K; 1989=31,307K. Captures managerial/supervisory workers per Mohun's class decomposition.\n"),

    "ES1503": ("Total Unproductive Labor (Mohun 2013)", "**Status**: book_period_validated. Source: same Mohun decomposition CSV, column `Lu_mohun` = Luw + Lum. 1948=14,096K; 1989=55,981K. The full unproductive labor count under Mohun's narrow classification.\n"),

    "ES1504": ("Unproductive Burden Ratio Lu/Lp (Mohun 2013)", "**Status**: book_period_validated. Derived: ES1503 / Mohun's Lp_total. Range over 1948-1989: 0.7614 - 0.9228. Rises secularly, confirming Mohun's finding that unproductive labor grows faster than productive labor under his classification.\n"),

    "ES1101": ("Net Transfer Rate (Shaikh & Tonak 1987)", "**Chapter**: External study — ST 1987. **Status**: book_period_validated. **Period**: 1952-1989. **Units**: share of EC.\n\nDerived: `(S605 + S606 - S604) / S617` = (B_w + G_w - T_w) / EC. The ST 1987 paper's headline measure: the fraction of total compensation that workers receive back from the state net of taxes. Range 1952-1989: [-0.0653, +0.0207] — i.e., -6.5% to +2.1% of total wage bill. Negative most years, brief positive episodes.\n\n## Citation\n\nShaikh, Anwar, and E. Ahmet Tonak. 1987. 'The Welfare State and the Myth of the Social Wage,' in Robert Cherry et al., eds., *The Imperiled Economy*, Vol. I. URPE.\n"),

    "ES1102": ("Social Benefit Rate (S&T 1987)", "**Status**: book_period_validated. Derived: `(S605 + S606) / S617`. Range 1952-1989: [0.2162, 0.3493]. Workers receive 22-35% of total compensation back as benefits + government services.\n"),

    "ES1103": ("Social Tax Rate (S&T 1987)", "**Status**: book_period_validated. Derived: `S604 / S617`. Range 1952-1989: [0.2616, 0.3627]. Workers pay 26-36% of total compensation back to state via taxes. The MAGNITUDE of this rate vs ES1102 tells you whether NSW is net positive or negative.\n"),
}

for sid, (name, body) in DPRS.items():
    text = f"# {sid} — {name}\n\n" + body + "\n---\n\n*Generated by anu-ingestion.*\n"
    (OUT / f"{sid}_DPR.md").write_text(text, encoding="utf-8")
    print(f"Wrote {sid}_DPR.md")

# Update S607 DPR to reflect extension activation
s607_path = OUT / "S607_DPR.md"
if s607_path.exists():
    existing = s607_path.read_text(encoding="utf-8")
    extension_note = """
## Extension activated (2026-05-14)

S607 now spans **1952-2025** (74 years) via concat of:
- S607-A: Table6_3_NetSocialWage.csv (book, 1952-1989)
- S607-B: Table6_3_Extended.csv (1990-2025, same NIPA methodology)

**Headline regime change**: NSW first POSITIVE in 1975 (a brief 1970s positive episode), but the *persistent* sign change is in the 1990s as transfer programs (Medicare expansion, EITC) outpaced worker tax burden. 2024 NSW = $1,234B (positive).

Validator V03_S607 includes a regime_change_check that flags the first positive year.

"""
    if "Extension activated" not in existing:
        s607_path.write_text(existing + extension_note, encoding="utf-8")
        print("Updated S607_DPR.md with extension activation note")
