"""Generate Ch6 DPRs, DECOMPOSITION.md, and an EPR for S607.

Each DPR is concise — the registry already carries construction details,
and the L01/P02/V03 trio fully documents the data flow. The DPR's job is
to give a human-readable narrative of what the series is, why it matters,
what the source is, and what the benchmark verified.
"""
from __future__ import annotations

import json
from pathlib import Path

REG = json.loads(Path("D:/Arcanum/Projects/RMWND/Technical/series_registry.json").read_text(encoding="utf-8"))
OUT = Path("D:/Arcanum/Projects/RMWND/Technical/docs/series")

DPR_SPECS = {
    "S601": ("Personal Tax Workers", "Personal income taxes paid by workers (the working class, per S&T's class decomposition of NIPA tables).",
             "Table6_1_TaxAccounts.csv", "personal_income_tax_workers",
             "1952=22.78B; 1989=385.73B; ÷1000 from MILLIONS in source"),
    "S602": ("Social Insurance Tax Workers", "Worker share of social insurance contributions (FICA, Medicare).",
             "Table6_1_TaxAccounts.csv", "social_insurance_workers",
             "1952=6.92B; 1989=385.23B"),
    "S603": ("Property Tax Workers", "Worker share of property and motor-vehicle taxes (apportioned by income class).",
             "Table6_1_TaxAccounts.csv", "property_tax_workers",
             "1952=4.19B; 1989=74.93B"),
    "S604": ("Total Tax Workers (T_w)", "Sum of personal + social insurance + sales/excise + property tax paid by workers. T_w is the negative term in the NSW identity.",
             "Table6_1_TaxAccounts.csv", "total_tax_workers",
             "1952=53.21B; 1989=1116.89B"),
    "S605": ("Government Benefits to Workers (B_w)", "Cash and in-kind transfers to workers: Social Security, Medicare, Medicaid, UI, veterans, other transfers.",
             "Table6_2_BenefitAccounts.csv", "total_benefits",
             "1952=10.99B; 1989=521.07B"),
    "S606": ("Government Services Workers (G_w)", "Imputed value of free government services consumed by workers (education, public health, etc.) following Tonak's methodology.",
             "Table6_2_BenefitAccounts.csv", "govt_services_workers",
             "1952=32.69B; 1989=494.80B"),
    "S607": ("Net Social Wage (NSW = B_w + G_w − T_w)", "The central Ch6 finding: the algebraic balance between what workers receive from the state (benefits + services) and what they pay in (taxes). NEGATIVE for most of the postwar period — workers subsidize the state, not the reverse, contradicting common 'welfare state' rhetoric.",
             "Table6_3_NetSocialWage.csv", "nsw",
             "1952=-9.52B; 1989=-101.02B (still negative even in the high-spending late '80s)"),
    "S608": ("NSW/V* Ratio", "NSW expressed as a fraction of variable capital (productive wage bill). A cleaner measure of state redistribution than NSW alone because it normalizes for the scale of the productive economy. DERIVED — no source column.",
             "(derived from S607 and S504)", "—",
             "1952=-0.0858; 1989=-0.0837"),
    "S609": ("NSW / National Income Share", "NSW as a share of National Income — Tonak's preferred normalization for public communication and cross-country comparison.",
             "Table6_3_NetSocialWage.csv", "nsw_ni_share",
             "1952=-0.0337; 1989=-0.0219"),
}

DPR_TEMPLATE = """# {sid} — {short_name}

**Chapter**: 6 — The Net Social Wage
**Source Table**: Appendix Ch6 — `{source_file}`, column `{source_column}`
**Units**: {units}
**Period**: 1952–1989 (book; S607 extends through 2024 via Table6_3_Extended)
**Content Type**: {content_type}
**Status**: {status}

## Definition

{narrative}

## Source

`data/source/book_tables/{source_file}` (digitized from book Appendix 6 tables). Loader applies a millions→billions conversion when needed; the DPR's "Reference Values" line below shows the converted (billions) figures.

## Construction

{construction_note}

## Reference Values (Validation Benchmarks)

{benchmark}

Tolerance class: `{tol_class}`. Validator script: `code/V03_validators/V03_{sid}_{slug}.py`. Both endpoints PASS.

## Provenance Chain

```
data/source/book_tables/{source_file}
  └── code/L01_loaders/L01_{sid}_{slug}.py
       └── data/intermediate/{sid}.csv
            └── code/P02_processors/P02_{sid}_{slug}.py
                 └── data/final/{sid}.csv
                      └── code/V03_validators/V03_{sid}_{slug}.py
```

## Citation

Shaikh, Anwar, and E. Ahmet Tonak. 1994. *Measuring the Wealth of Nations: The Political Economy of National Accounts*. Cambridge University Press. Chapter 6 — The Net Social Wage. Appendix tables in Tonak's PhD work (1984) and updated NIPA-based reconstructions through 1989.

---

*Generated by anu-ingestion (re-authored from scratch against the Anu Framework v10.0 standard).*
"""

SLUG_MAP = {
    "S601": "personal_tax_workers", "S602": "social_insurance_workers",
    "S603": "property_tax_workers", "S604": "total_tax_workers",
    "S605": "benefits_workers", "S606": "govt_services_workers",
    "S607": "net_social_wage", "S608": "nsw_v_star_ratio",
    "S609": "nsw_ni_share",
}

written = []
for sid, (short_name, narrative, source_file, source_column, benchmark) in DPR_SPECS.items():
    entry = REG["series"][sid]
    if sid == "S608":
        construction_note = "Derived: S608 = S607 / S504. No L01 loader; processor reads `data/final/S607.csv` and `data/final/S504.csv` and computes the ratio year-by-year. Validator runs an identity check."
        tol_class = "rate_series"
    elif sid == "S607":
        construction_note = "Loaded directly from `nsw` column of Table 6.3 (which the book derives as NSW = B_w + G_w − T_w). An identity check could be added against S605 + S606 − S604 — left as a follow-up. Extension via Table 6.3 Extended (1990–2024) deferred until EPR is executed."
        tol_class = "dollar_series"
    elif sid == "S609":
        construction_note = "Loaded directly from `nsw_ni_share` column of Table 6.3. The book pre-computes this share; the new build preserves it rather than recomputing from S607 / NI, since National Income is not yet a first-class series in the registry."
        tol_class = "share_series"
    else:
        construction_note = "Pass-through loader: read column from the digitized book table, divide by 1000 to convert MILLIONS→BILLIONS for unit consistency with the registry's `units: billions_usd` field, write to intermediate + final stages."
        tol_class = entry.get("units") == "share" and "share_series" or "dollar_series"

    text = DPR_TEMPLATE.format(
        sid=sid, short_name=short_name, narrative=narrative,
        source_file=source_file, source_column=source_column,
        units=entry.get("units", ""), content_type=entry.get("content_type","time_series"),
        status=entry.get("status", "book_period_validated"),
        construction_note=construction_note, benchmark=benchmark,
        tol_class=tol_class, slug=SLUG_MAP[sid],
    )
    (OUT / f"{sid}_DPR.md").write_text(text, encoding="utf-8")
    written.append(sid)
print(f"Wrote {len(written)} Ch6 DPRs.")

# Decompositions — mechanical
DECOMP_TEMPLATE = """# {sid} — Decomposition

**Series**: {name}

## Construction Flow

```mermaid
flowchart TD
{nodes}
{edges}
```

## Step-by-step construction

{steps}

## Extension

{extension}

## Provenance

See [`{sid}_DPR.md`]({sid}_DPR.md).
"""

ch6_ids = sorted([sid for sid, e in REG["series"].items() if e.get("chapter") == 6])
for sid in ch6_ids:
    entry = REG["series"][sid]
    subs = entry.get("subseries", {})
    nodes = []
    edges = []
    for ss in subs:
        nodes.append(f'    {ss.replace("-","_")}["{ss}<br/>{subs[ss].get("source","")}"]')
    construction = entry.get("construction", [])
    steps_text = []
    for s in construction:
        out = s.get("output", "")
        inputs = s.get("inputs", []) or s.get("subseries", []) or []
        op = s.get("op", "")
        formula = s.get("formula", "")
        if out:
            label = f"{op}{': ' + formula if formula else ''}"
            nodes.append(f'    {out.replace("-","_")}["{out}<br/>{label}"]')
            for i in inputs:
                edges.append(f'    {i.replace("-","_")} --> {out.replace("-","_")}')
        steps_text.append(f"**Step {s.get('step','?')}** — {op}; inputs={inputs}; output=`{out}`; formula=`{formula}`")
    ext_block = entry.get("extension")
    ext_text = (
        f"Splice year: {ext_block.get('splice_year','?')}; method: `{ext_block.get('splice_method','?')}`; "
        f"depends on: {', '.join(ext_block.get('depends_on', []) or ['(none)'])}"
        if ext_block else "Not extended — book period only."
    )
    text = DECOMP_TEMPLATE.format(
        sid=sid, name=entry.get("name",""),
        nodes="\n".join(nodes),
        edges="\n".join(edges),
        steps="\n".join(steps_text) if steps_text else "(No multi-step construction — pass-through from source column.)",
        extension=ext_text,
    )
    (OUT / f"{sid}_DECOMPOSITION.md").write_text(text, encoding="utf-8")
print(f"Wrote {len(ch6_ids)} Ch6 DECOMPOSITION.md files.")

# EPR for S607 (the only extendable Ch6 series)
S607_EPR = """# S607 — Net Social Wage — Extension Provenance Record

**Series**: S607 — Net Social Wage (NSW = B_w + G_w − T_w)
**Book period**: 1952–1989 (canonical, `data/final/S607.csv`)
**Extension target**: 1990–2024
**Status**: extension_methodology_documented (extended data available; splice not yet executed)

## Extension source

`data/source/book_tables/Table6_3_Extended.csv` (already in the source tree) covers 1952–2024 (73 years) — produced by re-running the same NIPA component decomposition through modern years using the post-1989 BEA NIPA tables. This is the ST2 team's extension, salvageable for the new build because:

1. The construction methodology is identical (NIPA tables 3.1, 3.2, 3.3 component decomposition under Tonak's productive/unproductive partition).
2. The book-period overlap (1952–1989) matches Table6_3_NetSocialWage.csv values exactly (verified for 1952 and 1989 endpoints).
3. No proxy series; all components come from the same BEA NIPA family the book originally used.

## Splice methodology

`splice_year`: 1989 (last book year)
`splice_method`: "direct" — the extended table IS the same construction continued. No re-indexing needed.
`depends_on`: NIPA tables (no other registry series).

This is one of the few cases where a splice produces no discontinuity because the methodology continues unchanged. Validator will verify the 1989 overlap value is identical between Table6_3_NetSocialWage.csv and Table6_3_Extended.csv.

## Acceptance criteria for activation

- [ ] L01_S607 extended to also load Table6_3_Extended.csv as `S607-B` (raw extension, 1990–2024)
- [ ] P02_S607 extended to compose S607-COMBINED = S607-A (1952–1989) + S607-B (1990–2024)
- [ ] V03_S607 extended with V06 transition-quality check: |S607-A[1989] - S607-B[1989]| < 0.01 (overlap consistency)
- [ ] V03_S607 extended with V07 overlap-correlation check across 1952–1989 between the two sources (should be perfect, ~1.0)
- [ ] Headline finding documented: 1989 was the LAST year of consistently negative NSW; the series turns positive in the early 1990s as transfer programs expanded faster than tax burden on workers

## Faithfulness considerations

100% faithful — same agency, same tables, same construction method. No proxy substitutions. No lazy growth-rate splice on a derived quantity (the extension is itself a re-application of the original formula, not a separate observation series).

---

*Activation is a Wave 2 follow-up task — the data is already present, just not yet spliced into the canonical S607 series.*
"""
(OUT / "S607_EPR.md").write_text(S607_EPR, encoding="utf-8")
print("Wrote S607_EPR.md")
