"""Generate a Markdown replication report from processing results."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any


def generate_replication_report(
    results: list[dict[str, Any]],
    output_path: str | Path,
    *,
    title: str = "Replication Report",
    version: str = "1.0.0",
) -> Path:
    """Write a REPLICATION_REPORT.md summarising the pipeline run."""
    output_path = Path(output_path)
    if output_path.is_dir():
        output_path = output_path / "REPLICATION_REPORT.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    ok = sum(1 for r in results if r.get("status") == "ok")
    warn = sum(1 for r in results if r.get("status") == "warn")
    fail = sum(1 for r in results if r.get("status") == "fail")
    total = len(results)

    lines: list[str] = []
    _a = lines.append

    _a(f"# {title}")
    _a("")
    _a(f"**Generated**: {now}  ")
    _a(f"**Pipeline version**: {version}  ")
    _a(f"**Series processed**: {total}  ")
    _a("")
    _a("---")
    _a("")
    _a("## Summary")
    _a("")
    _a("| Metric | Count |")
    _a("|--------|------:|")
    _a(f"| Total series | {total} |")
    _a(f"| Passed       | {ok} |")
    _a(f"| Warnings     | {warn} |")
    _a(f"| Failed       | {fail} |")
    _a("")
    _a("## Series Detail")
    _a("")

    for r in results:
        sid = r.get("series_id", "unknown")
        status = r.get("status", "unknown")
        icon = {"ok": "\u2713", "warn": "\u26a0", "fail": "\u2717"}.get(status, "?")
        _a(f"### {icon} {sid}")
        _a("")

        steps = r.get("steps", [])
        if steps:
            _a("| Step | Status | Detail |")
            _a("|------|--------|--------|")
            for i, step in enumerate(steps, 1):
                if isinstance(step, dict):
                    s_icon = {"ok": "\u2713", "warn": "\u26a0", "fail": "\u2717"}.get(step.get("status", ""), "\u00b7")
                    _a(f"| {step.get('name', '?')} | {s_icon} {step.get('status', '')} | {step.get('detail', '')} |")
                else:
                    _a(f"| {i} | \u00b7 | {step} |")
            _a("")

        validation = r.get("validation")
        if validation:
            _a("**Validation checks:**")
            _a("")
            for v in validation:
                v_icon = "\u2713" if v.get("within_tolerance") else "\u2717"
                _a(
                    f"- {v_icon} Year {v.get('year')}: "
                    f"expected {v.get('expected')}, got {v.get('actual'):.4f} "
                    f"(err {v.get('rel_error', 0):.4%})"
                )
            _a("")

    _a("---")
    _a("")
    _a(f"*Report generated by AS2 Anu Replicator v{version}*")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path.resolve()
