#!/usr/bin/env bash
# Install the RMWND precommit_check.py as a git pre-commit hook.
#
# Usage:
#     bash Technical/code/utils/install_precommit_hook.sh
#
# Behavior:
#   - If $PROJECT_ROOT/.git exists: writes a pre-commit hook that runs the
#     check in --staged mode and chmods it executable.
#   - If no .git is present: prints the manual invocation form and exits 0
#     without writing anything (the project's history was scrubbed of nested
#     .git repos during the v0.4 hyper-review honesty pass).
#
# Hook semantics:
#   - Non-zero exit code from precommit_check.py aborts the commit.
#   - Bypass with `git commit --no-verify` (discouraged; investigate first).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# .../Technical/code/utils -> project root is three levels up.
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
GIT_DIR="${PROJECT_ROOT}/.git"
HOOK_PATH="${GIT_DIR}/hooks/pre-commit"
CHECK_PATH="Technical/code/utils/precommit_check.py"

if [ ! -d "${GIT_DIR}" ]; then
    echo "No .git/ found at ${PROJECT_ROOT}."
    echo "Use the manual invocation form instead:"
    echo ""
    echo "    python ${CHECK_PATH} --all"
    echo ""
    echo "(The RMWND project was scrubbed of nested .git repos in the v0.4"
    echo " hyper-review honesty pass; re-init a repo at the project root if"
    echo " you want auto-enforcement via this hook.)"
    exit 0
fi

mkdir -p "${GIT_DIR}/hooks"
cat > "${HOOK_PATH}" <<'HOOK'
#!/usr/bin/env bash
# RMWND pre-commit hook — Decisions 0001-0008.
# Generated by Technical/code/utils/install_precommit_hook.sh
set -e
PROJECT_ROOT="$(git rev-parse --show-toplevel)"
exec python "${PROJECT_ROOT}/Technical/code/utils/precommit_check.py" --staged
HOOK

chmod +x "${HOOK_PATH}"
echo "Installed pre-commit hook: ${HOOK_PATH}"
echo "Test it now with: python ${CHECK_PATH} --all"
